create TABLE products (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 sku VARCHAR(40) NOT NULL UNIQUE,
 name VARCHAR(40) NOT NULL,
 price NUMERIC(12,2) NOT NULL CHECK (price > 0),
 stock INTEGER NOT NULL CHECK (stock > 0)
)

create TABLE purchase_orders (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 owner VARCHAR(100) NOT NULL,
 request_key VARCHAR(80) NOT NULL,
 product_id BIGINT NOT NULL REFERENCES products(id),
 quantity INTEGER NOT NULL CHECK (quantity>0)
 unit_price NUMERIC(12,2) NOT NULL (unit_price>0),
 total NUMERIC(18, 2) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 CONSTRAINT uk_order_request UNIQUE (owner, request_key)
)

CREATE INDEX idx_orders_product ON purchase_orders(product_id);